services:
  - name: "/scenario/websocket_fault"
    forwarder_service_suffix: "/forwarder/set_network_probabilities"
    drop_probability: 1
    packet_invalidity_probability: 0.0
    out_of_order_probability: 0.0
    delay_probability: 0.0
    drone_ids:
      - px4_1
      - px4_3
      - px4_4
      - px4_7
      - px4_10

  - name: "/scenario/zone_degradation"
    forwarder_service_suffix: "/forwarder/set_network_probabilities"
    drop_probability: 1
    packet_invalidity_probability: 0.0
    out_of_order_probability: 0.0
    delay_probability: 0.0
    drone_ids:
      - px4_2
      - px4_4
      - px4_7
      - px4_8

  - name: "/scenario/config_error"
    forwarder_service_suffix: "/forwarder/set_network_probabilities"
    drop_probability: 1
    packet_invalidity_probability: 0.0
    out_of_order_probability: 0.0
    delay_probability: 0.0
    drone_ids:
      - px4_1
      - px4_3
      - px4_4
      - px4_9